In [3]:
import pandas as pd
from pathlib import Path

In [8]:
metadata_raw = pd.read_csv("/home/m40ista/Projects/pd-transcriptomics-convergence/data/processed/SNCA/metadata.csv")

In [18]:
metadata_raw

,Run,Donor,genotype,source_name,treatment_condition/type,treatment
0,SRR11652312,Triplication SNCA,Triplication SNCA,Triplication SNCA_NSC,\,Control
1,SRR11652313,Triplication SNCA,Triplication SNCA,Triplication SNCA_WTPFF,WTPFF,Aggregation
2,SRR11652314,Triplication SNCA,Triplication SNCA,Triplication SNCA_PDamp,PDamp,Aggregation
3,SRR11652315,Triplication SNCA,Triplication SNCA,Triplication SNCA_MSAamp,MSAamp,Aggregation
4,SRR11652316,Triplication SNCA,Triplication SNCA,Triplication SNCA_NSC,NSC,Control
5,SRR11652317,Triplication SNCA,Triplication SNCA,Triplication SNCA_WTPFF,WTPFF,Aggregation
6,SRR11652318,Triplication SNCA,Triplication SNCA,Triplication SNCA_PDamp,PDamp,Aggregation
7,SRR11652319,Triplication SNCA,Triplication SNCA,Triplication SNCA_MSAamp,MSAamp,Aggregation
8,SRR11652320,Triplication SNCA,Triplication SNCA,Triplication SNCA_NSC,NSC,Control
9,SRR11652321,Triplication SNCA,Triplication SNCA,Triplication SNCA_WTPFF,WTPFF,Aggregation
10,SRR11652322,Triplication SNCA,Triplication SNCA,Triplication SNCA_PDamp,PDamp,Aggregation
11,SRR11652323,Triplication SNCA,Triplication SNCA,Triplication SNCA_MSAamp,MSAamp,Aggregation
12,SRR11652324,AH17,Control,Control_NSC,NSC,Control
13,SRR11652325,AH17,Control,Control_WTPFF,WTPFF,Aggregation
14,SRR11652326,AH17,Control,Control_PDamp,PDamp,Aggregation
15,SRR11652327,AH17,Control,Control_MSAamp,MSAamp,Aggregation
16,SRR11652328,OX3,Control,Control_NSC,NSC,Control
17,SRR11652329,OX3,Control,Control_WTPFF,WTPFF,Aggregation
18,SRR11652330,OX3,Control,Control_PDamp,PDamp,Aggregation
19,SRR11652331,OX3,Control,Control_MSAamp,MSAamp,Aggregation
20,SRR11652332,SFC840,Control,Control_NSC,NSC,Control
21,SRR11652333,SFC840,Control,Control_WTPFF,WTPFF,Aggregation
22,SRR11652334,SFC840,Control,Control_PDamp,PDamp,Aggregation
23,SRR11652335,SFC840,Control,Control_MSAamp,MSAamp,Aggregation

In [19]:
condicoes = ['Triplication SNCA_NSC', 'Control_NSC']
metadata_filtrado = metadata_raw[metadata_raw['source_name'].isin(condicoes)]

In [22]:
metadata_filtrado

,Run,Donor,genotype,source_name,treatment_condition/type,treatment
0,SRR11652312,Triplication SNCA,Triplication SNCA,Triplication SNCA_NSC,\,Control
4,SRR11652316,Triplication SNCA,Triplication SNCA,Triplication SNCA_NSC,NSC,Control
8,SRR11652320,Triplication SNCA,Triplication SNCA,Triplication SNCA_NSC,NSC,Control
12,SRR11652324,AH17,Control,Control_NSC,NSC,Control
16,SRR11652328,OX3,Control,Control_NSC,NSC,Control
20,SRR11652332,SFC840,Control,Control_NSC,NSC,Control

In [ ]:
metadata_final = metadata_filtrado[['Run', 'source_name']]
metadata_final

condition = {
    'Control_NSC': 'control',
    'Triplication SNCA_NSC': 'triplication'
}

metadata_final['condition'] = metadata_final['source_name'].map(condition)

metadata_final

            Run            source_name condition
0   SRR11652312  Triplication SNCA_NSC       NaN
4   SRR11652316  Triplication SNCA_NSC       NaN
8   SRR11652320  Triplication SNCA_NSC       NaN
12  SRR11652324            Control_NSC       NaN
16  SRR11652328            Control_NSC       NaN
20  SRR11652332            Control_NSC       NaN